server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   # 通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
